/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CampanasRouteImport } from './routes/campanas'
import { Route as ContenidoRouteImport } from './routes/contenido'
import { Route as FechasRouteImport } from './routes/fechas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PdfsRouteImport } from './routes/pdfs'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasRoute = CampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContenidoRoute = ContenidoRouteImport.update({
  id: '/contenido',
  path: '/contenido',
  getParentRoute: () => rootRouteImport,
} as any)
const FechasRoute = FechasRouteImport.update({
  id: '/fechas',
  path: '/fechas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfsRoute = PdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/campanas': typeof CampanasRoute
  '/contenido': typeof ContenidoRoute
  '/fechas': typeof FechasRoute
  '/login': typeof LoginRoute
  '/pdfs': typeof PdfsRoute
  '/register': typeof RegisterRoute
  '/tareas': typeof TareasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/campanas': typeof CampanasRoute
  '/contenido': typeof ContenidoRoute
  '/fechas': typeof FechasRoute
  '/login': typeof LoginRoute
  '/pdfs': typeof PdfsRoute
  '/register': typeof RegisterRoute
  '/tareas': typeof TareasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/campanas': typeof CampanasRoute
  '/contenido': typeof ContenidoRoute
  '/fechas': typeof FechasRoute
  '/login': typeof LoginRoute
  '/pdfs': typeof PdfsRoute
  '/register': typeof RegisterRoute
  '/tareas': typeof TareasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/campanas'
    | '/contenido'
    | '/fechas'
    | '/login'
    | '/pdfs'
    | '/register'
    | '/tareas'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/campanas'
    | '/contenido'
    | '/fechas'
    | '/login'
    | '/pdfs'
    | '/register'
    | '/tareas'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/campanas'
    | '/contenido'
    | '/fechas'
    | '/login'
    | '/pdfs'
    | '/register'
    | '/tareas'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CampanasRoute: typeof CampanasRoute
  ContenidoRoute: typeof ContenidoRoute
  FechasRoute: typeof FechasRoute
  LoginRoute: typeof LoginRoute
  PdfsRoute: typeof PdfsRoute
  RegisterRoute: typeof RegisterRoute
  TareasRoute: typeof TareasRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas': {
      id: '/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof CampanasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contenido': {
      id: '/contenido'
      path: '/contenido'
      fullPath: '/contenido'
      preLoaderRoute: typeof ContenidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fechas': {
      id: '/fechas'
      path: '/fechas'
      fullPath: '/fechas'
      preLoaderRoute: typeof FechasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfs': {
      id: '/pdfs'
      path: '/pdfs'
      fullPath: '/pdfs'
      preLoaderRoute: typeof PdfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CampanasRoute: CampanasRoute,
  ContenidoRoute: ContenidoRoute,
  FechasRoute: FechasRoute,
  LoginRoute: LoginRoute,
  PdfsRoute: PdfsRoute,
  RegisterRoute: RegisterRoute,
  TareasRoute: TareasRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
